export const imageRegistryAbi = [
  'error EmptyContentHash()',
  'error ImageNotRegistered(uint256 imageId)',
  'error CollectionNotRegistered(uint256 collectionId)',
  'error ImageHashAlreadyRegistered(bytes32 contentHash)',
  'error OnlyCollectionCreatorCanAddImages(uint256 collectionId, address caller)',
  'error OwnableUnauthorizedAccount(address account)',
  'error OwnableInvalidOwner(address owner)',
  'function registerCollection(string name, string metadataURI) returns (uint256)',
  'function registerImage(bytes32 contentHash, string metadataURI, uint256 collectionId) returns (uint256)',
  'function verifyImageHash(uint256 imageId, bytes32 candidateHash) view returns (bool)',
  'function getImage(uint256 imageId) view returns ((uint256 id, uint256 collectionId, address currentOwner, bytes32 contentHash, string metadataURI, uint64 registeredAt))',
  'function getCollectionWithImages(uint256 collectionId) view returns ((uint256 id, address creator, string name, string metadataURI, uint64 createdAt), (uint256 id, uint256 collectionId, address currentOwner, bytes32 contentHash, string metadataURI, uint64 registeredAt)[])',
  'event CollectionRegistered(uint256 indexed collectionId, address indexed creator, string name)',
  'event ImageRegistered(uint256 indexed imageId, uint256 indexed collectionId, address indexed creator, bytes32 contentHash, string metadataURI)',
] as const;

export const licensingAndPaymentAbi = [
  'error RegistryAddressIsZero()',
  'error OracleAddressIsZero()',
  'error CallerIsNotOracle(address caller)',
  'error ImageNotRegistered(uint256 imageId)',
  'error CallerIsNotImageOwner(uint256 imageId, address caller)',
  'error LicenseOfferNotActive(uint256 imageId)',
  'error IncorrectPaymentAmount(uint256 expected, uint256 actual)',
  'error OfferSellerIsOutdated(uint256 imageId, address expectedSeller, address actualSeller)',
  'error PurchaseDoesNotExist(uint256 purchaseId)',
  'error AccessAlreadyConfirmed(uint256 purchaseId)',
  'error NoFundsAvailable(address account)',
  'error WithdrawalFailed(address payee, uint256 amount)',
  'error OwnableUnauthorizedAccount(address account)',
  'error OwnableInvalidOwner(address owner)',
  'error EnforcedPause()',
  'error ExpectedPause()',
  'error ReentrancyGuardReentrantCall()',
  'function paused() view returns (bool)',
  'function setOracle(address newOracle)',
  'function pause()',
  'function unpause()',
  'function configureLicenseOffer(uint256 imageId, uint256 priceWei, string termsURI, bool active)',
  'function buyLicense(uint256 imageId) payable returns (uint256)',
  'function confirmDownloadAccess(uint256 purchaseId, bytes32 accessProof)',
  'function withdrawPayments()',
  'function getLicenseOffer(uint256 imageId) view returns ((uint256 imageId, address seller, uint256 priceWei, string termsURI, bool active))',
  'function getPurchase(uint256 purchaseId) view returns ((uint256 id, uint256 imageId, address buyer, address seller, uint256 paidAmount, bytes32 accessProof, uint64 purchasedAt))',
  'function getMyPurchases() view returns ((uint256 id, uint256 imageId, address buyer, address seller, uint256 paidAmount, bytes32 accessProof, uint64 purchasedAt)[])',
  'function getMySales() view returns ((uint256 id, uint256 imageId, address buyer, address seller, uint256 paidAmount, bytes32 accessProof, uint64 purchasedAt)[])',
  'event Paused(address account)',
  'event Unpaused(address account)',
  'event LicensePurchased(uint256 indexed purchaseId, uint256 indexed imageId, address indexed buyer, address seller, uint256 paidAmount)',
] as const;

export const modelAndIndexAuditAbi = [
  'error EmptyModelVersion()',
  'error EmptyIndexVersion()',
  'error EmptyModelHash()',
  'error EmptyIndexHash()',
  'error SnapshotDoesNotExist(uint256 snapshotId)',
  'error OwnableUnauthorizedAccount(address account)',
  'error OwnableInvalidOwner(address owner)',
  'function recordSnapshot(string modelVersion, bytes32 modelHash, string indexVersion, bytes32 indexHash, string metadataURI) returns (uint256)',
  'function getSnapshot(uint256 snapshotId) view returns ((uint256 id, string modelVersion, bytes32 modelHash, string indexVersion, bytes32 indexHash, string metadataURI, address submittedBy, uint64 recordedAt))',
  'function verifySnapshot(uint256 snapshotId, bytes32 expectedModelHash, bytes32 expectedIndexHash) view returns (bool)',
  'event AuditSnapshotRecorded(uint256 indexed snapshotId, string modelVersion, bytes32 indexed modelHash, string indexVersion, bytes32 indexed indexHash, string metadataURI, address submittedBy)',
] as const;